/**
 * Catalogue multi-formations — CAS Academy
 * Campus Analyse & Suivi
 */
window.ADA_CATALOG = {
  campus: {
    brand: "CAS Academy",
    shortBrand: "CAS",
    fullName: "Campus Analyse & Suivi",
    name: "CAS Academy",
    title: "Campus Analyse & Suivi",
    lede: "Une plateforme. Deux formations métier. Objectif : maîtrise opérationnelle junior — comprendre, transférer, justifier, détecter les erreurs.",
    tagline: "Analyser. Suivre. Décider.",
  },
  packs: [
    {
      id: "data-analyst",
      title: "Data Analyst",
      shortTitle: "DA",
      tagline: "De la collecte terrain à la décision — maîtrise opérationnelle junior.",
      accent: "da",
      audience: "Analystes, chargés de données, cadres programmes",
      outcome: "Maîtrise opérationnelle junior de la chaîne Data Analyst (transfert + justifications)",
      duration: "52–78 h",
      modulesCount: 11,
      badge: "Parcours métier",
      highlights: ["Excel & Stats", "Kobo · SQL · Python", "SIG · Qualité", "IA · Éthique"],
      modules: [
        {
          id: "01-excel",
          order: 1,
          title: "Excel",
          subtitle: "Autonomie analyste & préparation",
          duration: "6–8 h",
          blurb: "Formules ($), RECHERCHEX, Power Query, TCD multi-champs — épreuve fichier sale.",
          entry: "01_excel-atelier/index.html",
        },
        {
          id: "02-stats",
          order: 2,
          title: "Statistiques",
          subtitle: "Décision sous incertitude",
          duration: "5–7 h",
          blurb: "Indicateurs, échantillon, causalité prudente, labo transfert — quiz ≥ 80 %.",
          entry: "02_stats-atelier/index.html",
        },
        {
          id: "03-collecte",
          order: 3,
          title: "Collecte",
          subtitle: "Kobo, échantillon & QC source",
          duration: "5–7 h",
          blurb: "XLSForm, échantillonnage, pilote/déploiement — épreuve brief stock.",
          entry: "03_collecte-atelier/index.html",
        },
        {
          id: "04-sql",
          order: 4,
          title: "SQL",
          subtitle: "Interrogation avancée & transfert",
          duration: "6–8 h",
          blurb: "JOIN, HAVING, CTE, fenêtre — épreuve multi-tables sans guide.",
          entry: "04_sql-atelier/index.html",
        },
        {
          id: "05-python",
          order: 5,
          title: "Python",
          subtitle: "Automatisation & pièges pandas",
          duration: "7–9 h",
          blurb: "Pandas, merges, groupby — épreuve transfert CSV sale.",
          entry: "05_python-atelier/index.html",
        },
        {
          id: "06-powerbi",
          order: 6,
          title: "Power BI",
          subtitle: "Design, modèle & DAX",
          duration: "6–8 h",
          blurb: "Dashboard pro, modèle étoile, mesures/CALCULATE, épreuve brief logistique.",
          entry: "06_powerbi-atelier/index.html",
        },
        {
          id: "07-storytelling",
          order: 7,
          title: "Storytelling",
          subtitle: "Note de décision",
          duration: "3–4 h",
          blurb: "Transformer l’analyse en récit clair et actionnable.",
          entry: "07_storytelling-atelier/index.html",
        },
        {
          id: "08-sig",
          order: 8,
          title: "SIG",
          subtitle: "QC GPS, CRS & couverture",
          duration: "5–7 h",
          blurb: "CRS, jointures, analyse couverture — épreuve transfert spatiale.",
          entry: "sig-atelier/index.html?pack=data-analyst",
        },
        {
          id: "09-qualite",
          order: 9,
          title: "Qualité",
          subtitle: "Gouvernance & go/no-go",
          duration: "5–7 h",
          blurb: "Règles QC, journal, épreuve go/no-go sur dataset inconnu.",
          entry: "qualite-atelier/index.html?pack=data-analyst",
        },
        {
          id: "10-ia",
          order: 10,
          title: "IA",
          subtitle: "Usage responsable comme levier",
          duration: "3–4 h",
          blurb: "Prompts et vérification — après maîtrise des fondamentaux et du go/no-go.",
          entry: "08_ia-atelier/index.html",
        },
        {
          id: "11-ethique",
          order: 11,
          title: "Éthique",
          subtitle: "Protection & partage responsable",
          duration: "4–6 h",
          blurb: "Sensibilité, minimisation — justification éthique écrite (épreuve).",
          entry: "ethique-atelier/index.html?pack=data-analyst",
        },
      ],
    },
    {
      id: "se",
      title: "Expert S&E",
      shortTitle: "S&E",
      tagline: "Suivi & Évaluation — maîtrise opérationnelle junior (spécialisation autonome).",
      accent: "se",
      audience: "Chargés S&E/MEAL, coordinateurs, cadres projets",
      outcome: "Maîtrise opérationnelle junior d’un système S&E (transfert + jugement go/no-go)",
      duration: "48–68 h",
      modulesCount: 12,
      badge: "Parcours métier",
      highlights: ["Cadre de résultats", "Maîtrise & SIG", "Qualité & dossier", "Éthique & AAP"],
      modules: [
        {
          id: "se-01-metier",
          order: 1,
          title: "Métier S&E",
          subtitle: "Pilotage, rôles, éthique",
          duration: "3–4 h",
          blurb: "Situer le S&E dans le cycle projet ; do-no-harm et redevabilité.",
          entry: "se-atelier/index.html",
        },
        {
          id: "se-02-cadre",
          order: 2,
          title: "Cadre de résultats",
          subtitle: "Chaîne de résultats",
          duration: "3–4 h",
          blurb: "Activités → outputs → outcomes → impact, hypothèses et risques.",
          entry: "se-atelier/index.html",
        },
        {
          id: "se-03-indicateurs",
          order: 3,
          title: "Indicateurs",
          subtitle: "Dictionnaire, baseline, cibles",
          duration: "4–5 h",
          blurb: "Fiches indicateurs utiles, calcul commun, désagrégation.",
          entry: "se-atelier/index.html",
        },
        {
          id: "se-04-plan",
          order: 4,
          title: "Plan de suivi",
          subtitle: "Matrice & calendrier",
          duration: "3–4 h",
          blurb: "Qui collecte quoi, quand, pour quelles décisions.",
          entry: "se-atelier/index.html",
        },
        {
          id: "se-05-collecte",
          order: 5,
          title: "Collecte S&E",
          subtitle: "Indicateur → données",
          duration: "4–5 h",
          blurb: "Sources, outils, éthique et AAP léger.",
          entry: "se-atelier/index.html",
        },
        {
          id: "se-06-qualite",
          order: 6,
          title: "Qualité & analyse",
          subtitle: "QC et écarts",
          duration: "3–4 h",
          blurb: "Contrôles qualité et lecture décisionnelle des écarts.",
          entry: "se-atelier/index.html",
        },
        {
          id: "se-07-reporting",
          order: 7,
          title: "Reporting",
          subtitle: "Note & pilotage",
          duration: "3–4 h",
          blurb: "Reporting actionnable et recommandations assignées.",
          entry: "se-atelier/index.html",
        },
        {
          id: "se-08-maitrise",
          order: 8,
          title: "Maîtrise S&E",
          subtitle: "Échantillon, indicateur, go/no-go",
          duration: "4–6 h",
          blurb: "Jugement opérationnel : couverture, utilité d’indicateur, éval légère et seuil de publication.",
          entry: "se-atelier/index.html",
        },
        {
          id: "se-09-sig",
          order: 9,
          title: "SIG S&E",
          subtitle: "Couverture spatiale & décisions",
          duration: "4–6 h",
          blurb: "Cartographier couverture vs cible et assigner des décisions de pilotage.",
          entry: "sig-atelier/index.html?pack=se",
        },
        {
          id: "se-10-qualite",
          order: 10,
          title: "Qualité S&E",
          subtitle: "Seuils, go/no-go & redevabilité",
          duration: "4–6 h",
          blurb: "Exiger la qualité avant de piloter : seuils d’acceptation et décision de publication.",
          entry: "qualite-atelier/index.html?pack=se",
        },
        {
          id: "se-11-evaluation",
          order: 11,
          title: "Évaluation & dossier",
          subtitle: "Questions & dossier S&E",
          duration: "4–5 h",
          blurb: "Dossier défendable après évidence spatiale et go/no-go — épreuve carnet D.",
          entry: "se-atelier/index.html",
        },
        {
          id: "se-12-ethique",
          order: 12,
          title: "Éthique S&E",
          subtitle: "Consentement, AAP & partage",
          duration: "3–5 h",
          blurb: "Protéger les populations : consentement, minimisation et décisions de partage.",
          entry: "ethique-atelier/index.html?pack=se",
        },
      ],
    },
  ],
  upcoming: [],
};
