/**
 * Catalogue multi-formations — CAS Academy
 * Campus Analyse & Suivi
 */
window.ADA_CATALOG = {
  campus: {
    brand: "CAS Academy",
    shortBrand: "CAS",
    fullName: "Campus Analyse & Suivi",
    name: "CAS Academy",
    title: "Campus Analyse & Suivi",
    lede: "Une plateforme. Deux formations métier. Choisissez Data Analyst ou Expert S&E — analyse des données et suivi-évaluation pour décider avec des preuves.",
    tagline: "Analyser. Suivre. Décider.",
  },
  packs: [
    {
      id: "data-analyst",
      title: "Data Analyst",
      shortTitle: "DA",
      tagline: "De la collecte terrain à la décision — qualité, SIG, éthique et IA.",
      accent: "da",
      audience: "Analystes, chargés de données, cadres programmes",
      outcome: "Maîtriser la chaîne Data Analyst opérationnelle",
      duration: "43–62 h",
      modulesCount: 11,
      badge: "Parcours métier",
      highlights: ["Excel & Stats", "Kobo · SQL · Python", "SIG & Qualité", "Éthique · IA"],
      modules: [
        {
          id: "01-excel",
          order: 1,
          title: "Excel",
          subtitle: "Analyse & préparation des données",
          duration: "4–6 h",
          blurb: "Formules, filtres, TCD et graphiques pour décider avec des tableaux.",
          entry: "01_excel-atelier/index.html",
        },
        {
          id: "02-stats",
          order: 2,
          title: "Statistiques",
          subtitle: "Analyse statistique appliquée",
          duration: "3–5 h",
          blurb: "Lire les chiffres, éviter les pièges, appuyer une recommandation.",
          entry: "02_stats-atelier/index.html",
        },
        {
          id: "03-collecte",
          order: 3,
          title: "Collecte",
          subtitle: "KoboToolbox & qualité des données",
          duration: "4–6 h",
          blurb: "Concevoir une collecte terrain fiable et contrôler la qualité.",
          entry: "03_collecte-atelier/index.html",
        },
        {
          id: "04-sql",
          order: 4,
          title: "SQL",
          subtitle: "Interrogation & agrégation",
          duration: "5–7 h",
          blurb: "Extraire et agréger des données avec SQL dans le navigateur.",
          entry: "04_sql-atelier/index.html",
        },
        {
          id: "05-python",
          order: 5,
          title: "Python",
          subtitle: "Automatisation & analyse approfondie",
          duration: "6–8 h",
          blurb: "Automatiser le traitement et approfondir l’analyse avec Python.",
          entry: "05_python-atelier/index.html",
        },
        {
          id: "06-powerbi",
          order: 6,
          title: "Power BI",
          subtitle: "Visualisation décisionnelle",
          duration: "4–6 h",
          blurb: "Tableaux de bord et choix de visuels pour la décision.",
          entry: "06_powerbi-atelier/index.html",
        },
        {
          id: "07-storytelling",
          order: 7,
          title: "Storytelling",
          subtitle: "Note de décision",
          duration: "3–4 h",
          blurb: "Transformer l’analyse en récit clair et actionnable.",
          entry: "07_storytelling-atelier/index.html",
        },
        {
          id: "08-ia",
          order: 8,
          title: "IA",
          subtitle: "Usage responsable comme levier",
          duration: "3–4 h",
          blurb: "Prompts, vérification et IA après maîtrise des fondamentaux.",
          entry: "08_ia-atelier/index.html",
        },
        {
          id: "09-sig",
          order: 9,
          title: "SIG",
          subtitle: "Analyse spatiale & QC GPS",
          duration: "4–6 h",
          blurb: "Fiabiliser les couches, joindre les zones et produire une carte utile à la décision.",
          entry: "sig-atelier/index.html?pack=data-analyst",
        },
        {
          id: "10-qualite",
          order: 10,
          title: "Qualité",
          subtitle: "Gouvernance & contrôle des données",
          duration: "4–6 h",
          blurb: "Dictionnaire, règles QC, journal et fichier clean avant toute analyse.",
          entry: "qualite-atelier/index.html?pack=data-analyst",
        },
        {
          id: "11-ethique",
          order: 11,
          title: "Éthique",
          subtitle: "Protection des données",
          duration: "3–5 h",
          blurb: "Minimisation, exports safe et IA sans données personnelles.",
          entry: "ethique-atelier/index.html?pack=data-analyst",
        },
      ],
    },
    {
      id: "se",
      title: "Expert S&E",
      shortTitle: "S&E",
      tagline: "Suivi & Évaluation opérationnel standard — cas d’exercice humanitaire Kalunga.",
      accent: "se",
      audience: "Chargés S&E/MEAL, coordinateurs, cadres projets",
      outcome: "Concevoir et faire vivre un système S&E utile au pilotage",
      duration: "39–55 h",
      modulesCount: 11,
      badge: "Parcours métier",
      highlights: ["Cadre de résultats", "SIG & Qualité", "Éthique & AAP", "Reporting"],
      modules: [
        {
          id: "se-01-metier",
          order: 1,
          title: "Métier S&E",
          subtitle: "Pilotage, rôles, éthique",
          duration: "3–4 h",
          blurb: "Situer le S&E dans le cycle projet ; do-no-harm et redevabilité.",
          entry: "se-atelier/index.html",
        },
        {
          id: "se-02-cadre",
          order: 2,
          title: "Cadre de résultats",
          subtitle: "Chaîne de résultats",
          duration: "3–4 h",
          blurb: "Activités → outputs → outcomes → impact, hypothèses et risques.",
          entry: "se-atelier/index.html",
        },
        {
          id: "se-03-indicateurs",
          order: 3,
          title: "Indicateurs",
          subtitle: "Dictionnaire, baseline, cibles",
          duration: "4–5 h",
          blurb: "Fiches indicateurs utiles, calcul commun, désagrégation.",
          entry: "se-atelier/index.html",
        },
        {
          id: "se-04-plan",
          order: 4,
          title: "Plan de suivi",
          subtitle: "Matrice & calendrier",
          duration: "3–4 h",
          blurb: "Qui collecte quoi, quand, pour quelles décisions.",
          entry: "se-atelier/index.html",
        },
        {
          id: "se-05-collecte",
          order: 5,
          title: "Collecte S&E",
          subtitle: "Indicateur → données",
          duration: "4–5 h",
          blurb: "Sources, outils, éthique et AAP léger.",
          entry: "se-atelier/index.html",
        },
        {
          id: "se-06-qualite",
          order: 6,
          title: "Qualité & analyse",
          subtitle: "QC et écarts",
          duration: "3–4 h",
          blurb: "Contrôles qualité et lecture décisionnelle des écarts.",
          entry: "se-atelier/index.html",
        },
        {
          id: "se-07-reporting",
          order: 7,
          title: "Reporting",
          subtitle: "Note & pilotage",
          duration: "3–4 h",
          blurb: "Reporting actionnable et recommandations assignées.",
          entry: "se-atelier/index.html",
        },
        {
          id: "se-08-evaluation",
          order: 8,
          title: "Évaluation & dossier",
          subtitle: "Questions & dossier S&E",
          duration: "3–4 h",
          blurb: "Questions évaluatives et dossier défendable, méthode transférable.",
          entry: "se-atelier/index.html",
        },
        {
          id: "se-09-sig",
          order: 9,
          title: "SIG S&E",
          subtitle: "Couverture spatiale & décisions",
          duration: "4–6 h",
          blurb: "Cartographier couverture vs cible et assigner des décisions de pilotage.",
          entry: "sig-atelier/index.html?pack=se",
        },
        {
          id: "se-10-qualite",
          order: 10,
          title: "Qualité S&E",
          subtitle: "Seuils, go/no-go & redevabilité",
          duration: "4–6 h",
          blurb: "Exiger la qualité avant de piloter : seuils d’acceptation et décision de publication.",
          entry: "qualite-atelier/index.html?pack=se",
        },
        {
          id: "se-11-ethique",
          order: 11,
          title: "Éthique S&E",
          subtitle: "Consentement, AAP & partage",
          duration: "3–5 h",
          blurb: "Protéger les populations : consentement, minimisation et décisions de partage.",
          entry: "ethique-atelier/index.html?pack=se",
        },
      ],
    },
  ],
  upcoming: [],
};
